CREATE TABLE FRIENDS (
   "ID" INTEGER not null primary key,
   "NAME" VARCHAR(256)
);

INSERT INTO FRIENDS VALUES (1, 'Mike');
INSERT INTO FRIENDS VALUES (2, 'James');
INSERT INTO FRIENDS VALUES (3, 'Jerilyn');
INSERT INTO FRIENDS VALUES (4, 'Jonathan');
