CREATE TABLE FRIENDS (
   "ID" INTEGER not null primary key,
    "NAME" VARCHAR(256)
);

INSERT INTO COLLEAGUES VALUES (1,'Mike);
INSERT INTO COLLEAGUES VALUES (2, 'James');
INSERT INTO COLLEAGUES VALUES (3, 'Jerilyn');
INSERT INTO COLLEAGUES VALUES (4, 'Jonathan');
